/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wcs.java.basics.bean.test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.io.File;

import org.junit.Before;
import org.junit.Test;

import com.wcs.java.basics.bean.Car;
import com.wcs.java.basics.bean.CarSerializer;
import com.wcs.java.basics.bean.Driver;

public class CarTest {
	
	public final static String FILENAME = "./car.serialized";
	
	@Before
	public  void setUp() {
		File f = new File(FILENAME);
		if (f.exists()) {
			f.delete();
		}
	}
	
	@Test
	public void writeToCar() throws Exception{
		
		Car car = new Car("BMW");
		Driver driver = new Driver("David");
		car.setDriver(driver);
		
		CarSerializer.writeCarToFile(car, new File(FILENAME));
		
		File f = new File(FILENAME);
		assertTrue("File is written: ", f.exists());
		
	}
	
	@Test
	public void readFromCar() throws Exception{
		//must write before
		writeToCar();
		
		Car car = CarSerializer.readCarFromFile(new File(FILENAME));
		
		assertNotNull(car);
		assertEquals("Should be BMW", "BMW", car.getBrandName());
		
		assertNotNull(car.getDriver());
		assertEquals("Should be Driver David", "David", car.getDriver().getFirstName());
		
	}
}
